org: episodes
app: episodes
service: episodes

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: app/handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    noPrependStageInUrl: true
